version: '3'
services:
  service:
    build:
      context: .
      args:
        JAR_FILE: amazing-co-1.0-SNAPSHOT.jar
    ports:
      - "25555:8080"
    restart: always
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: postgres-dockerfile
    container_name: postgres
    restart: always